---
deployment:
  tasks:
    - export DEPLOYPATH=/home/berandad/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R public/* $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - cd $DEPLOYPATH && php artisan migrate --force
    - cd $DEPLOYPATH && php artisan optimize:clear
